apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modularcommerce
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shop.changehere.org
      secretName: shop-tls
  rules:
    - host: shop.changehere.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modularcommerce-api
                port:
                  number: 80
