apiVersion: batch/v1
kind: Job
metadata:
  name: modularcommerce-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/onurnafiguzel/modularcommerce:a21e2bc884a9d7cb8a617fbfbc089ba20bd35dcc
          env:
            - name: RUN_MIGRATIONS
              value: "true"
          envFrom:
            - configMapRef:
                name: modularcommerce-config
            - secretRef:
                name: modularcommerce-secrets
