apiVersion: v1
kind: Secret
metadata:
  name: modularcommerce-secrets
type: Opaque
stringData:
  ConnectionStrings__Database: "Host=postgres;Port=5432;Database=modular_commerce;Username=postgres;Password=postgres"
  ConnectionStrings__Redis: "redis:6379"
  ConnectionStrings__RabbitMq: "amqp://guest:guest@rabbitmq:5672"
