// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularCommerce.Cart.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModularCommerce.Cart.Infrastructure.Migrations
{
    [DbContext(typeof(CartDbContext))]
    partial class CartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cart")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModularCommerce.Cart.Infrastructure.Persistence.CartRecord", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.ToTable("carts", "cart");
                });

            modelBuilder.Entity("ModularCommerce.Cart.Infrastructure.Persistence.CartRecord", b =>
                {
                    b.OwnsMany("ModularCommerce.Cart.Infrastructure.Persistence.CartItemRecord", "Items", b1 =>
                        {
                            b1.Property<Guid>("CartRecordCustomerId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("AddedAtUtc");

                            b1.Property<Guid>("ProductId");

                            b1.Property<int>("Quantity");

                            b1.HasKey("CartRecordCustomerId", "__synthesizedOrdinal");

                            b1.ToTable("carts", "cart");

                            b1
                                .ToJson("Items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CartRecordCustomerId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
